[package]
name = "globaltokentracker-ui"
version.workspace = true
edition = "2024"

[dependencies]
globaltokentracker-core = { workspace = true }
crossbeam-channel = "0.5.15"
notify = "8.2.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tray-icon = "0.25.1"
windows = { version = "0.62.2", features = [
    "Win32_Globalization",
    "Win32_Graphics_DirectWrite",
] }
windows-canvas = { version = "0.100.0", features = ["reactor"] }
windows-sys = { version = "0.60.2", features = [
    "Win32_Foundation",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_System_Registry",
    "Win32_Storage_FileSystem",
] }
windows-reactor = "=0.100.0"
windows-time = { version = "0.100.0", default-features = false }
windows-composition = { version = "0.100.0", default-features = false, features = ["reactor"] }

[build-dependencies]
winresource = "0.1"
